### ISSUE TITLE
Incomplete information during retrieval

### ISSUE THREAD

**Issue by king009** [bkader/skeleton#5] opened 2018-03-30 05:49 UTC
I don't know if should it be really added as a bug or a feature. :laughing: 

When we retrieve any type of entity, we get the corresponding details from group/object table.. But not from metadata. I have to recall get_meta for the guid to fetch other details. How about that get_<entity types> can give me the metadata as well? Should we join the metadata table?

**Comment by bkader** [comment] 2018-03-30 09:22
You cannot join metadata because of its structure. You should use the meta key as column name and it’s value as, obviously, the value.  
On the next update, I will provide a dump of sql with tables and views. You use the regular one or the one with views.  
Anyways, I will see what I can do with including metadata. This is more of a feature, not a bug.

**Comment by bkader** [comment] 2018-03-30 13:53
On the next update, **users**, **groups** and **objects** libraries will return respective objects. To explain better:  

```php
// Retrieve the user:
$user = get_user(1);

// To access properties:
echo $user->username; // Entities table
echo $user->email;  // Users table.
echo $user->company; // Metadata

// TO enqueu changes:
$user->set('username', 'new_username');
$user->set('email', 'new_email@ffffff.com')
$user->set('company', 'new company');

// Then save them:
$user->save();

// To do changes without queuing them:
$user->update('username', 'new_username'); // Returns a boolean
$user->update('company', 'new company'); // Returns aboolean
// ... etc
```

What do you think? 😄

**Comment by bkader** [comment] 2018-04-05 02:51
Full data retrieval - from main tables or metadata - is available on the [develop](https://github.com/bkader/skeleton) and [master](https://github.com/bkader/skeleton/tree/master) branches. Once the full code revisited and checked, everything will be merged into the [stable](https://github.com/bkader/skeleton/tree/stable) branch and a new release will be created.

**Comment by bkader** [comment] 2018-04-06 16:09
The feature was added and a new release is out [1.3.0](https://github.com/bkader/skeleton/releases/tag/1.3.0).

**Closed as completed by bkader** 2018-04-06 16:09 UTC
Labels: feature
